=== raison024/WSD-Lab3/schema.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified" attributeFormDefault="unqualified">

<xs:element name="catalog">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="program" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="lead" type="xs:string"/>
            <xs:element name="genre" type="xs:string"/>
            <xs:element name="release" type="xs:date"/>
            
            <xs:element name="rating">
              <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-5]"/>
                  </xs:restriction>
              </xs:simpleType>
            </xs:element>

            <xs:element name="cat" >
              <xs:simpleType>
                <xs:restriction base="xs:string">
                      <xs:enumeration value="Movie"/>
                      <xs:enumeration value="TV Show"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>

          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
      
</xs:schema>

=== raison024/WSD-Lab3/data.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="transform.xsl"?>

<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">

    <program>
        <name>Inception</name>
        <lead>Leo</lead>
        <genre>Thriller</genre>
        <release>2002-09-24</release>
        <rating>4</rating>
        <cat>Movie</cat>
    </program>
    <program>
        <name>Tenet</name>
        <lead>Robert Pattinson</lead>
        <genre>Sci-fi</genre>
        <release>2010-08-12</release>
        <rating>5</rating>
        <cat>Movie</cat>
    </program>
    <program>
        <name>Big Boss</name>
        <lead>Salman Khan</lead>
        <genre>Drama</genre>
        <release>2018-12-01</release>
        <rating>2</rating>
        <cat>TV Show</cat>
    </program>
    <program>
        <name>The Prestige</name>
        <lead>Christian Bale</lead>
        <genre>Mystery</genre>
        <release>2020-10-28</release>
        <rating>5</rating>
        <cat>Movie</cat>
    </program>
    <program>
        <name>Stranger Things</name>
        <lead>Tovino</lead>
        <genre>Adventure</genre>
        <release>2011-12-20</release>
        <rating>4</rating>
        <cat>TV Show</cat>
    </program>
    <program>
        <name>Avengers</name>
        <lead>Robert Downey</lead>
        <genre>Action</genre>
        <release>2010-10-20</release>
        <rating>3</rating>
        <cat>Movie</cat>
    </program>
    
</catalog>
